services:
  mariadb:
    image: mariadb:10.11
    container_name: price-comparator-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: 123456
      MARIADB_DATABASE: price_comparator_db
      MARIADB_USER: comparator_user
      MARIADB_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: "mariadb-admin ping -h localhost -u$$MARIADB_USER -p$$MARIADB_PASSWORD"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: price-comparator-app
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/price_comparator_db
      SPRING_DATASOURCE_USERNAME: comparator_user
      SPRING_DATASOURCE_PASSWORD: 123456
      APP_CSV_INPUT_PATH: /data-input
    volumes:
      - ./src/main/data-input:/data-input
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src

volumes:
  mariadb_data: